# Generated by Django 4.0.6 on 2022-08-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_dni_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SOCIO', 'Socio'), ('VISITANTE', 'Visitante')], default='VISITANTE', max_length=12, verbose_name='Role'),
        ),
    ]
