# Generated by Django 4.0.6 on 2022-08-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_logevents_user_login_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Número de logueos'),
        ),
    ]
