# Generated by Django 4.0.6 on 2022-08-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
